name             'cp-microservice'
maintainer       'Phenompeople Pvt Ltd'
maintainer_email 'admin.squad@phenompeople.com'
license          'Apache 2.0'
description      'Installs/Configures cp-microservice'
long_description 'Installs/Configures cp-microservice'
version          '0.1.0'
