---
driver:
  name: vagrant
  network:
    - ["forwarded_port", { guest: 8080, host: 8080, auto_correct: true }]

provisioner:
  name: chef_zero

platforms:
  - name: awslinux
    driver_config:
      box: awslinux_2016.09
  - name: centos-7.3
    driver_config:
      box: centos_7.3.1611
  - name: centos-7.2
    driver_config:
      box: centos_7.2.1511
  - name: ubuntu-16.04
    driver_config:
      box: ubuntu_16.04
  - name: ubuntu-14.04
    drive_config:
      box: ubuntu_14.04

suites:
  - name: default
    run_list:
      - recipe[ntp::install_client]
      - recipe[ntp::service]
      - recipe[docker::install]
      - recipe[docker::service]
      - recipe[docker::wrappers]
      - recipe[basic-essentials::install_pip]
      - recipe[aws::cli_install]
      - recipe[aws::ecr_login]
      - recipe[seo-service::docker_deploy]
    attributes:
      aws:
        region: us-east-1
        sdk_gem_version: 2.7.15
        account_id: 716533421362
      phenom:
        admin_email: admin.squid@phenompeople.com