name             'seo-service'
maintainer       'Phenompeople Pvt Ltd'
maintainer_email 'admin.squad@phenompeople.com'
license          'Apache 2.0'
description      'Installs/Configures seo-service'
long_description 'Installs/Configures seo-service'
source_url		   'https://bitbucket.org/maheimom/chef-cookbooks'
issues_url		   'https://bitbucket.org/maheimom/chef-cookbooks/issues'
depends          'aws'
depends          'docker'
depends          'ntp'
version          '0.1.1'
