name             'filebeat'
maintainer       'Phenompeople Pvt Ltd'
maintainer_email 'admin.squad@phenompeople.com'
license          'Apache 2.0'
description      'Installs/Configures filebeat'
long_description 'Installs/Configures filebeat'
source_url       'https://bitbucket.org/maheimom/chef-cookbooks'
issues_url       'https://bitbucket.org/maheimom/chef-cookbooks/issues'
depends          'basic-essentials'
version          '0.1.1'
