---
driver:
  name: docker
  use_sudo: false

provisioner:
  name: chef_zero

platforms:

  - name: amazon-201703
    driver_config:
      image: phenompeople/amazonlinux-ccb:2017.03
      platform: centos
      privileged: true
      volume: /sys/fs/cgroup
      privileged: true
      remove_images: false

  - name: amazon-201609
    driver_config:
      image: phenompeople/amazonlinux-ccb:2016.09
      platform: centos
      privileged: true
      volume: /sys/fs/cgroup
      privileged: true
      remove_images: false

  - name: centos-7.3
    driver_config:
      image: phenompeople/centos-ccb:7.3.1611
      platform: centos
      run_command: /usr/sbin/init
      privileged: true
      forward:
        - 5004:5004
      memory: 2048MB
      volume: /sys/fs/cgroup
      remove_images: true
  - name: centos-7.2
    driver_config:
      image: phenompeople/centos-ccb:7.2.1511
      platform: centos
      run_command: /usr/sbin/init
      privileged: true
      forward: 5004
      volume:
      - /sys/fs/cgroup
      remove_images: true

  - name: ubuntu14.04
    driver_config:
      image: phenompeople/ubuntu-ccb:14.04
      platform: ubuntu
      forward: 5004
      remove_images: true

  - name: ubuntu16.04
    driver_config:
      image: phenompeople/ubuntu-ccb:16.04
      run_options: '--security-opt seccomp=unconfined --stop-signal=SIGRTMIN+3 --tmpfs /run --tmpfs /run/lock -v /sys/fs/cgroup:/sys/fs/cgroup:ro'
      run_command: '/sbin/init'
      forward: 5004
      platform: ubuntu
      remove_images: true
suites:
  - name: default
    run_list:
      - recipe[basic-essentials::gitclient]
      - recipe[build-essentials::deploy_user_assemble]
      - recipe[phenomtrackapi::configure]

    attributes:
      aws_account_id: "716533421362"
      aws_region: "us-east-1"
      zookeeper:
        cluster:  ["qa-kafka01"]
      kafka:
        cluster:  ["qa-kafka01"]
