name             'phenomtrackapi'
maintainer       'Phenompeople Pvt Ltd'
maintainer_email 'admin.squad@phenompeople.com'
license          'Apache 2.0'
description      'Installs/Configures phenomtrack-api'
long_description 'Installs/Configures phenomtrack-api'
source_url		   'https://bitbucket.org/maheimom/chef-cookbooks'
issues_url		   'https://bitbucket.org/maheimom/chef-cookbooks/issues'
chef_version     '>= 12.5' if respond_to?(:chef_version)
supports         'redhat'
depends          'kafka'
depends          'zookeeper'
version          '0.1.2'
