name             'apache-storm'
maintainer       'Phenompeople Pvt Ltd'
maintainer_email 'admin.squad@phenompeople.com'
license          'Apache 2.0'
description      'Installs/Configures storm'
long_description 'Installs/Configures storm'
source_url		   'https://bitbucket.org/maheimom/chef-cookbooks'
issues_url		   'https://bitbucket.org/maheimom/chef-cookbooks/issues'
chef_version     '>= 12.5' if respond_to?(:chef_version)
supports         'redhat'
depends          'basic-essentials'
depends          'zookeeper'
version          '0.1.0'
