name             'docker'
maintainer       'Rajesh Jonnalagadda'
maintainer_email 'rajesh.jonnalagadda@phenompeople.com'
license          'All rights reserved'
description      'Installs/Configures docker'
long_description 'Installs/Configures docker'
source_url		   'https://bitbucket.org/maheimom/chef-cookbooks'
issues_url		   'https://bitbucket.org/maheimom/chef-cookbooks/issues'
version          '0.1.0'
