name             'metricbeat'
maintainer       'Phenompeople Pvt Ltd'
maintainer_email 'admin.squad@phenompeople.com'
license          'Apache 2.0'
description      'Installs/Configures metricbeat'
long_description 'Installs/Configures metricbeat'
source_url       'https://bitbucket.org/maheimom/chef-cookbooks'
issues_url       'https://bitbucket.org/maheimom/chef-cookbooks/issues'
depends			     'basic-essentials'
version          '0.1.0'
