---
driver:
  name: docker
  use_sudo: false

provisioner:
  name: chef_zero

platforms:
  - name: amazon-2017.03
    driver_config:
      image: phenompeople/amazonlinux-ccb:2017.03
      platform: centos
      privileged: true
      volume: /sys/fs/cgroup
      remove_images: false

#  - name: amazon-2016.09
#    driver_config:
#      image: phenompeople/amazonlinux-ccb:2016.09
#      platform: centos
#      privileged: true
#      volume: /sys/fs/cgroup
#      remove_images: false
#
#  - name: centos-7.3
#    driver_config:
#      image: phenompeople/centos-ccb:7.3.1611
#      platform: centos
#      run_command: /usr/sbin/init
#      privileged: true
#      volume: /sys/fs/cgroup
#      remove_images: true
#
#
#  - name: centos-7.2
#    driver_config:
#      image: phenompeople/centos-ccb:7.2.1511
#      platform: centos
#      run_command: /usr/sbin/init
#      privileged: true
#      volume:
#      - /sys/fs/cgroup
#      remove_images: false
#
suites:
  - name: default
    run_list:
      - recipe[mongodb::install]
      - recipe[mongodb::configure]
      - recipe[mongodb::service]
    attributes:
      phenom:
        banner: 'Dont edit by Hand !!! This file is modified by Chef. Please contact admin.squad@phenompeople.com for further assitance'
      mongodb:
        replication_name: 'rs0'

  - name: master
    run_list:
      - recipe[mongodb::install]
#      - recipe[mongodb::fine_tunning]
#      - recipe[mongodb::master]
#      - recipe[mongodb::configure]
#      - recipe[mongodb::service]
    attributes:
      phenom:
        banner: 'Dont edit by Hand !!! This file is modified by Chef. Please contact admin.squad@phenompeople.com for further assitance'
      mongodb:
        replication_name: 'rs0'
