name             'ntp'
maintainer       'Phenompeople Pvt Ltd'
maintainer_email 'admin.squad@phenompeople.com'
license          'Apache 2.0'
description      'Installs/Configures ntp'
long_description 'Installs/Configures ntp'
source_url       'https://bitbucket.org/maheimom/chef-cookbooks'
issues_url       'https://bitbucket.org/maheimom/chef-cookbooks/issues'
version          '0.1.6'
