---
driver:
  name: docker
  use_sudo: false

provisioner:
  name: chef_zero

platforms:
  - name: amazon-2017.03
    driver_config:
      image: phenompeople/amazonlinux-ccb:2017.03
      platform: centos
      privileged: true
      volume: /sys/fs/cgroup
      privileged: true
      remove_images: false

  - name: amazon-2016.09
    driver_config:
      image: phenompeople/amazonlinux-ccb:2016.09
      platform: centos
      privileged: true
      volume: /sys/fs/cgroup
      privileged: true
      remove_images: false

  - name: centos-7.3
    driver_config:
      image: phenompeople/centos-ccb:7.3.1611
      platform: centos
      run_command: /usr/sbin/init
      privileged: true
      volume:
        - /sys/fs/cgroup:/sys/fs/cgroup
      remove_images: false

  - name: centos-7.2
    driver_config:
      image: phenompeople/centos-ccb:7.2.1511
      platform: centos
      run_command: /usr/sbin/init
      privileged: true
      volume:
        - /sys/fs/cgroup:/sys/fs/cgroup
      remove_images: true

  - name: ubuntu-14.04
    driver_config:
      image: phenompeople/ubuntu-ccb:14.04
      platform: ubuntu
      remove_images: true

  - name: ubuntu-16.04
    driver_config:
      image: phenompeople/ubuntu-ccb:16.04
      platform: ubuntu
      remove_images: true

suites:
  - name: default
    run_list:
      - recipe[basic-essentials::install_pip]
      - recipe[aws::cli_install]
      - recipe[aws::remove_profile]
    attributes:
      aws_account_id: "413928405733"
      aws_region: "us-east-1"
#        access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
#        access_secret_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
