---
driver:
  name: docker
  use_sudo: false

provisioner:
  name: chef_zero
  environments_path: ../environments
  cookbook_path:
    - ../cookbooks


platforms:
  - name: amazon-2017.03
    driver_config:
      image: phenompeople/amazonlinux-ccb:2017.03
      platform: centos
      privileged: true
      forward: 9200
      volume: /sys/fs/cgroup
      remove_images: true
  - name: amazon-2016.09
    driver_config:
      image: phenompeople/amazonlinux-ccb:2016.09
      platform: centos
      privileged: true
      forward: 9200
      volume: /sys/fs/cgroup
      remove_images: true

  - name: centos-7.3
    driver_config:
      image: phenompeople/centos-ccb:7.3.1611
      platform: centos
      run_command: /usr/sbin/init
      privileged: true
      volume:
       - /sys/fs/cgroup:/sys/fs/cgroup
#       - /Users/rajeshj/workspace/repos/CentOS/7.3:/etc/yum.repos.d/
      forward: 9200
      remove_images: true

  - name: centos-7.2
    driver_config:
      image: phenompeople/centos-ccb:7.2.1511
      platform: centos
      run_command: /usr/sbin/init
      privileged: true
      volume:
        - /sys/fs/cgroup:/sys/fs/cgroup
 #       - /Users/rajeshj/workspace/repos/CentOS/7.2:/etc/yum.repos.d/
      forward:
        - 9200
      remove_images: true

  - name: ubuntu16.04
    driver_config:
      image: phenompeople/ubuntu-ccb:16.04
      platform: ubuntu
      run_options: '--security-opt seccomp=unconfined --stop-signal=SIGRTMIN+3 --tmpfs /run --tmpfs /run/lock -v /sys/fs/cgroup:/sys/fs/cgroup:ro'
      run_command: '/sbin/init'
      forward: 9200
      remove_images: true

  - name: ubuntu14.04
    driver_config:
      image: phenompeople/ubuntu-ccb:14.04
      platform: ubuntu
      forward: 9200
      remove_images: true

suites:
  - name: default
    run_list:
      - recipe[basic-essentials::elastic_repo]
      - recipe[basic-essentials::oracle_java_default]
      - recipe[elasticsearch::install_from_repo]
#      - recipe[elasticsearch::cluster_configure]
#      - recipe[nginx::install]
#      - recipe[nginx::service]
#      - recipe[elasticsearch::curator]
#      - recipe[elasticsearch::service]
      # - recipe[elasticsearch::uninstall]
      # - recipe[basic-essentials::oracle_java_default_uninstall]
      # - recipe[basic-essentials::elastic_repo_uninstall]
    attributes:
      phenom:
        banner: 'This file managed by Admin'
      es_cluster_name: "QA_CP_ES_NEW"
      elasticsearch:
        package:
          version: 5.3.0-1

  - name: candidates
    run_list:
      - recipe[basic-essentials::oracle_java_default]
      - recipe[elasticsearch::install_from_archive]
      - recipe[elasticsearch::cluster_configure]
      - recipe[elasticsearch::plugins]
#      - recipe[nginx::install]
#      - recipe[nginx::service]
      - recipe[elasticsearch::service]

    attributes:
      phenom:
        banner: 'This file managed by Admin'
      es_cluster_name: "QA_CP_ES_NEW"
      elasticsearch:
        package:
          version: 2.3.5


