---
driver:
  name: docker
  use_sudo: false

provisioner:
  name: chef_zero

platforms:
  - name: amazon
    driver_config:
      image: phenompeople/amazonlinux:2016.09
      platform: centos
      privileged: true
      volume: /sys/fs/cgroup
      privileged: true

  - name: centos-7.3
    driver_config:
      image: phenompeople/centos:7.3.1611
      platform: centos
      run_command: /usr/sbin/init
      privileged: true
      volume:
        - /sys/fs/cgroup:/sys/fs/cgroup
        - /Users/rajeshj/workspace/repos/CentOS/7.3:/etc/yum.repos.d/
      remove_images: false

  - name: centos-7.2
    driver_config:
      image: phenompeople/centos:7.2
      platform: centos
      run_command: /usr/sbin/init
      privileged: true
      volume:
        - /sys/fs/cgroup:/sys/fs/cgroup
        - /Users/rajeshj/workspace/repos/CentOS/7.2:/etc/yum.repos.d/
      remove_images: false

  - name: ubuntu-14.04
    driver_config:
      image: phenompeople/ubuntu:14.04
      platform: ubuntu

  - name: ubuntu-16.04
    driver_config:
      image: phenompeople/ubuntu:16.04
      platform: ubuntu

suites:
  - name: default
    run_list:
      - recipe[basic-essentials::oracle_java_default]
      - recipe[basic-essentials::gitclient]
      - recipe[basic-essentials::chefdk_uninstall]
    attributes:
