name             'basic-essentials'
maintainer       'Rajesh Jonnalagadda'
maintainer_email 'rajesh.jonnalagadda@phenompeople.com'
license          'All rights reserved'
description      'configure basic-essentials for other cookbooks'
long_description 'Installs/Configures basic-essentials'
source_url		   'https://bitbucket.org/maheimom/chef-cookbooks'
issues_url		   'https://bitbucket.org/maheimom/chef-cookbooks/issues'
version          '0.1.1'
