name             'basic-essentials'
maintainer       'Phenompeople Pvt Ltd'
maintainer_email 'admin.squad@phenompeople.com'
license          'Apache 2.0'
description      'configure basic-essentials for other cookbooks'
long_description 'Installs/Configures basic-essentials'
source_url		   'https://bitbucket.org/maheimom/chef-cookbooks'
issues_url		   'https://bitbucket.org/maheimom/chef-cookbooks/issues'
chef_version     '>= 12.5' if respond_to?(:chef_version)
supports         'redhat'
supports         'debain'
version          '0.1.13'