name             'cms-tenant-service'
maintainer       'Phenompeople Pvt Ltd'
maintainer_email 'admin.squad@phenompeople.com'
license          'Apache 2.0'
description      'Installs/Configures cms-tenant-service'
long_description 'Installs/Configures cms-tenant-service'
version          '0.1.0'
