name             'mysql'
maintainer       'Phenompeople Pvt Ltd'
maintainer_email 'admin.squad@phenompeople.com'
license          'Apache 2.0'
description      'Installs/Configures mysql'
long_description 'Installs/Configures mysql'
chef_version     '>= 12.5' if respond_to?(:chef_version)
supports         'redhat'
supports         'debain'
source_url		   'https://bitbucket.org/maheimom/chef-cookbooks'
issues_url		   'https://bitbucket.org/maheimom/chef-cookbooks/issues'
version          '0.0.3'
