---
driver:
  name: docker
  use_sudo: false

provisioner:
  name: chef_zero

platforms:
  - name: centos-7.3
    driver_config:
      image: phenompeople/centos-ccb:7.3.1611
      platform: centos
      run_command: /usr/sbin/init
      privileged: true
      forward:
        - 5004:5004
      memory: 2048MB
      volume: /sys/fs/cgroup
      remove_images: true
  - name: centos-7.2
    driver_config:
      image: phenompeople/centos-ccb:7.2.1511
      platform: centos
      run_command: /usr/sbin/init
      privileged: true
      forward: 5004
      volume:
      - /sys/fs/cgroup
      remove_images: true

  - name: ubuntu14.04
    driver_config:
      image: phenompeople/ubuntu-ccb:14.04
      platform: ubuntu
      forward: 5004
      remove_images: true

  - name: ubuntu16.04
    driver_config:
      image: phenompeople/ubuntu-ccb:16.04
      run_options: '--security-opt seccomp=unconfined --stop-signal=SIGRTMIN+3 --tmpfs /run --tmpfs /run/lock -v /sys/fs/cgroup:/sys/fs/cgroup:ro'
      run_command: '/sbin/init'
      forward: 5004
      platform: ubuntu
      remove_images: true
suites:
  - name: default
    run_list:
      - recipe[basic-essentials::elastic_repo]
      - recipe[basic-essentials::oracle_java_default]
      - recipe[logstash::install]
      - recipe[logstash::configure]
      - recipe[logstash::service]

    attributes:
      phenom:
        banner: 'Dont edit by Hand !!! This file is managed by Chef. Please contact admin.squad@phenompeople.com for further assitance'
      logstash:
        certificate_name: "_default"
      elasticsearch:
        server_name: "127.0.0.1"
        server_port: "9200"

