name             'cp-emailcampaign'
maintainer       'Phenompeople Pvt Ltd'
maintainer_email 'admin.squad@phenompeople.com'
license          'Apache 2.0'
description      'Installs/Configures cp-emailcampaign'
long_description 'Installs/Configures cp-emailcampaign'
source_url		 'https://bitbucket.org/maheimom/chef-cookbooks'
issues_url		 'https://bitbucket.org/maheimom/chef-cookbooks/issues'
version          '0.1.0'
