name             'apache'
maintainer       'Phenompeople Pvt Ltd'
maintainer_email 'admin.squad@phenompeople.com'
license          'Apache 2.0'
description      'Installs/Configures apache'
long_description 'Installs/Configures apache'
chef_version     '>= 12.5' if respond_to?(:chef_version)
supports         'redhat','debain'
source_url		   'https://bitbucket.org/maheimom/chef-cookbooks'
issues_url		   'https://bitbucket.org/maheimom/chef-cookbooks/issues'
version          '0.0.1'
